import numpy as np, math as m
from math import gamma
@reg(11)
def d_11_1():
    cv=Canvas(560,330)
    cv.title(280,22,"Bias vs variance, seen on a dartboard")
    rng=np.random.default_rng(5)
    def board(cx,cy,bias,var,label):
        for r in [36,24,12]: cv.raw(f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" stroke="{PAL["ink3"]}" stroke-width="1"/>')
        cv.circle(cx,cy,3,fill=PAL["amberF"])
        pts=rng.normal([bias[0],bias[1]],var,size=(8,2))
        for dx,dy in pts: cv.circle(cx+dx,cy+dy,3.2,fill=PAL["red"])
        cv.text(cx,cy+56,label,fill=PAL["ink2"],size=10,weight="600")
    board(160,108,(0,0),4.5,"low bias · low variance")
    board(410,108,(0,0),14,"low bias · high variance")
    board(160,236,(21,15),4.5,"high bias · low variance")
    board(410,236,(21,15),14,"high bias · high variance")
    caption(cv,"Bias = how far the cluster sits from the bullseye; variance = how scattered the shots are around it.")
    return "11.1",cv.svg()
@reg(11)
def d_11_2():
    cv=Canvas(560,300)
    cv.title(280,22,"Maximum likelihood picks the parameter that best fits the data")
    F=Frame(cv,58,50,440,202,-0.02,1.02,-0.05,1.16)
    F.axes(xlabel="θ  (coin's heads-probability)")
    k,n=7,10; L=lambda t:(t**k)*((1-t)**(n-k))
    xs=np.linspace(0.001,0.999,180); mx=max(L(x) for x in xs)
    cv.poly([F.P(x,L(x)/mx) for x in xs],stroke=PAL["indigo"],w=2.4)
    that=k/n
    cv.line(F.X(that),F.Y(0),F.X(that),F.Y(1.0),stroke=PAL["red"],w=1.7,dash="4 3")
    cv.dot(F.X(that),F.Y(1.0),fill=PAL["red"])
    cv.text(F.X(that)+8,F.Y(1.02),"θ̂ = 7/10 = 0.7",fill=PAL["red"],size=11,weight="700",anchor="start")
    caption(cv,"Seven heads in ten flips: the likelihood peaks at θ = 0.7 — the MLE is just the observed frequency.")
    return "11.2",cv.svg()
@reg(11)
def d_11_3():
    cv=Canvas(560,300)
    cv.title(280,22,"MAP = likelihood × prior: the prior tugs the estimate")
    F=Frame(cv,58,50,440,202,-0.02,1.02,-0.05,1.18)
    F.axes(xlabel="θ")
    def bpdf(a,b): return lambda x:(x**(a-1)*(1-x)**(b-1))*gamma(a+b)/(gamma(a)*gamma(b)) if 0<x<1 else 0
    def nrm(f):
        xs=np.linspace(0.001,0.999,200); mx=max(f(x) for x in xs); return lambda x:f(x)/mx
    prior=nrm(bpdf(2,2)); lik=nrm(lambda t:(t**7)*((1-t)**3)); post=nrm(bpdf(9,5))
    xs=np.linspace(0.001,0.999,180)
    for f,col,lab,lx in [(prior,PAL["green"],"prior",0.5),(lik,PAL["blue"],"likelihood",0.78),(post,PAL["indigo"],"posterior",0.63)]:
        cv.poly([F.P(x,f(x)) for x in xs],stroke=col,w=2.2)
        cv.text(F.X(lx),F.Y(f(lx))-7,lab,fill=col,size=9.5,weight="600")
    mp=8/12; cv.line(F.X(mp),F.Y(0),F.X(mp),F.Y(1.0),stroke=PAL["red"],w=1.4,dash="4 3")
    cv.text(F.X(mp),F.Y(0)+15,"MAP 0.67",fill=PAL["red"],size=9.5,weight="700")
    caption(cv,"The posterior sits between the prior's 0.5 and the data's 0.7; MAP is its peak — a Gaussian prior gives L2.")
    return "11.3",cv.svg()
@reg(11)
def d_11_4():
    cv=Canvas(560,300)
    cv.title(280,22,"The bias–variance tradeoff: total error is a U-shape")
    F=Frame(cv,58,50,440,204,-0.1,5.1,-0.1,5.2)
    F.axes(xlabel="model complexity →",ylabel="error")
    bias2=lambda c:5.5/(c+0.7); var=lambda c:0.22*c**1.6; tot=lambda c:bias2(c)+var(c)
    xs=np.linspace(0.25,5,140)
    cv.poly([F.P(x,min(bias2(x),5.1)) for x in xs],stroke=PAL["blue"],w=2.0)
    cv.poly([F.P(x,min(var(x),5.1)) for x in xs],stroke=PAL["green"],w=2.0)
    cv.poly([F.P(x,min(tot(x),5.1)) for x in xs],stroke=PAL["red"],w=2.5)
    cs=np.linspace(0.3,4.8,300); copt=min(cs,key=lambda c:tot(c))
    cv.line(F.X(copt),F.Y(0),F.X(copt),F.Y(tot(copt)),stroke=PAL["ink3"],w=1,dash="3 3")
    cv.dot(F.X(copt),F.Y(tot(copt)),fill=PAL["red"])
    cv.text(F.X(3.4),F.Y(bias2(3.4))-8,"bias²",fill=PAL["blue"],size=10,weight="600",anchor="start")
    cv.text(F.X(4.2),F.Y(var(4.2))-8,"variance",fill=PAL["green"],size=10,weight="600",anchor="end")
    cv.text(F.X(1.3),F.Y(tot(1.3))+2,"total",fill=PAL["red"],size=10.5,weight="700",anchor="end")
    cv.text(F.X(copt),F.Y(tot(copt))-12,"sweet spot",fill=PAL["ink2"],size=9.5,weight="600")
    caption(cv,"Too simple → bias; too complex → variance. Best generalization sits at the bottom of the U.")
    return "11.4",cv.svg()
@reg(11)
def d_11_5():
    cv=Canvas(560,300)
    cv.title(280,22,"A p-value is the tail area beyond your observed result")
    F=Frame(cv,58,50,440,202,-3.8,3.8,-0.02,0.45)
    F.axes()
    pdf=lambda x:np.exp(-x*x/2)/np.sqrt(2*np.pi); xs=np.linspace(-3.7,3.7,170)
    cv.polygon([F.P(-3.7,0)]+[F.P(x,pdf(x)) for x in xs]+[F.P(3.7,0)],fill=PAL["blueF"],opacity=0.5)
    cv.poly([F.P(x,pdf(x)) for x in xs],stroke=PAL["indigo"],w=2.3)
    z=1.9; tail=[x for x in xs if x>=z]
    cv.polygon([F.P(z,0)]+[F.P(x,pdf(x)) for x in tail]+[F.P(tail[-1],0)],fill=PAL["red"],opacity=0.6)
    cv.line(F.X(z),F.Y(0),F.X(z),F.Y(pdf(z)+0.05),stroke=PAL["red"],w=1.7)
    cv.text(F.X(0),F.Y(0.18),"if H₀ were true",fill=PAL["ink2"],size=10,weight="600")
    cv.text(F.X(z)+6,F.Y(pdf(z)+0.06),"observed",fill=PAL["red"],size=10,weight="700",anchor="start")
    cv.text(F.X(2.9),F.Y(0.05),"p-value",fill=PAL["red"],size=10,weight="700")
    caption(cv,"If the null were true, how often would we see something this extreme? That red tail area is the p-value.")
    return "11.5",cv.svg()
